# Generated by Django 5.2 on 2025-10-09 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_tanam', models.DateField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pencatatan', models.DateTimeField(default=django.utils.timezone.now)),
                ('ph', models.FloatField()),
                ('ppm', models.PositiveIntegerField()),
                ('suhu_air', models.FloatField(verbose_name='Suhu Air (°C)')),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sensor', to='hidroponik.tanaman')),
            ],
            options={
                'ordering': ['-waktu_pencatatan'],
            },
        ),
    ]
