# Generated by Django 5.2.7 on 2025-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Dipanen', 'Dipanen')], default='Aktif', max_length=10),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='tanggal_panen_estimasi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
