# Generated by Django 5.2.7 on 2025-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0002_tanaman_status_tanaman_tanggal_panen_estimasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanaman',
            name='nama',
        ),
        migrations.AddField(
            model_name='tanaman',
            name='jenis_tanaman',
            field=models.CharField(choices=[('Bayam', 'Bayam'), ('Cabai', 'Cabai'), ('Caisim', 'Caisim'), ('Daun Bawang', 'Daun Bawang'), ('Kale', 'Kale'), ('Kangkung', 'Kangkung'), ('Pakcoy', 'Pakcoy'), ('Selada Air', 'Selada Air'), ('Seledri', 'Seledri'), ('Stroberi', 'Stroberi'), ('Timun', 'Timun'), ('Tomat', 'Tomat')], default='cabai', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanaman',
            name='media_tanam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='posisi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Posisi Rak/Tandon'),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='target_ph',
            field=models.FloatField(blank=True, null=True, verbose_name='Target pH Ideal'),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='target_ppm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='target_suhu',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Suhu (°C)'),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='varietas',
            field=models.CharField(blank=True, default='Tanpa Varietas', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='status',
            field=models.CharField(choices=[('Bibit', 'Bibit'), ('Aktif', 'Aktif'), ('Dipanen', 'Dipanen')], default='Bibit', max_length=10),
        ),
    ]
