# Generated by Django 5.2.7 on 2025-10-09 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0003_remove_tanaman_nama_tanaman_jenis_tanaman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasensor',
            old_name='suhu_air',
            new_name='suhu',
        ),
        migrations.RemoveField(
            model_name='datasensor',
            name='ppm',
        ),
        migrations.AddField(
            model_name='datasensor',
            name='ketinggian_air',
            field=models.FloatField(blank=True, null=True, verbose_name='Ketinggian Air (cm)'),
        ),
        migrations.AddField(
            model_name='datasensor',
            name='nutrisi_ppm',
            field=models.PositiveIntegerField(default=0, verbose_name='Tingkat Nutrisi (PPM)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasensor',
            name='ph',
            field=models.FloatField(verbose_name='pH Air'),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='status',
            field=models.CharField(choices=[('Bibit', 'Bibit'), ('Vegetatif', 'Vegetatif'), ('Berbunga', 'Berbunga/Berbuah'), ('Panen', 'Panen')], default='Bibit', max_length=10),
        ),
        migrations.CreateModel(
            name='FotoPerkembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_tanaman/')),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perkembangan', to='hidroponik.tanaman')),
            ],
            options={
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jenis_aktivitas', models.CharField(choices=[('Ganti Air', 'Ganti Air'), ('Tambah Nutrisi', 'Tambah Nutrisi'), ('Semprot Hama', 'Semprot Hama'), ('Pindah Tanaman', 'Pindah Tanaman')], max_length=50)),
                ('catatan', models.TextField()),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_aktivitas', to='hidroponik.tanaman')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
