# Generated by Django 5.2.7 on 2025-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0004_rename_suhu_air_datasensor_suhu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='catatan_panen',
            field=models.TextField(blank=True, verbose_name='Catatan Panen'),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='jumlah_hasil',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jumlah Hasil (berat/volume)'),
        ),
    ]
