# Generated by Django 5.2.7 on 2025-10-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0005_tanaman_catatan_panen_tanaman_jumlah_hasil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanaman',
            name='jumlah_hasil',
        ),
        migrations.AddField(
            model_name='tanaman',
            name='jumlah_hasil_angka',
            field=models.FloatField(blank=True, null=True, verbose_name='Jumlah Hasil'),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='satuan_hasil',
            field=models.CharField(blank=True, choices=[('gram', 'gram'), ('kg', 'kg')], default='gram', max_length=5),
        ),
    ]
