# Generated by Django 5.2.7 on 2025-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0006_remove_tanaman_jumlah_hasil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupukNutrisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Pupuk/Nutrisi')),
                ('pabrikan', models.CharField(blank=True, max_length=100)),
                ('jumlah', models.FloatField(verbose_name='Jumlah')),
                ('satuan', models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('gram', 'gram'), ('kg', 'kg')], default='ml', max_length=5)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
