# Generated by Django 5.2.7 on 2025-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0007_pupuknutrisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('jumlah', models.PositiveIntegerField(blank=True, null=True)),
                ('kategori', models.CharField(choices=[('Peralatan', 'Peralatan'), ('Media Tanam', 'Media Tanam'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
