# Generated by Django 5.2.7 on 2025-10-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0008_inventarisitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilTanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama harus sama dengan pilihan di Jenis Tanaman', max_length=100, unique=True)),
                ('estimasi_panen_hari', models.PositiveIntegerField()),
                ('ph_ideal_min', models.FloatField()),
                ('ph_ideal_max', models.FloatField()),
                ('ppm_ideal_min', models.PositiveIntegerField()),
                ('ppm_ideal_max', models.PositiveIntegerField()),
            ],
        ),
    ]
