# Generated by Django 5.2.7 on 2025-10-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0009_profiltanaman'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Token API dari BotFather Telegram', max_length=100)),
                ('chat_id', models.CharField(help_text='Chat ID pengguna atau grup Telegram', max_length=50)),
            ],
        ),
    ]
