# Generated by Django 5.2.7 on 2025-10-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0010_pengaturantelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaktivitas',
            name='jumlah_yang_digunakan',
            field=models.FloatField(blank=True, help_text='Jumlah pupuk/nutrisi yang digunakan (sesuai satuan di stok)', null=True),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='pupuk_yang_digunakan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hidroponik.pupuknutrisi'),
        ),
    ]
