# Generated by Django 5.2.7 on 2025-10-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponik', '0011_logaktivitas_jumlah_yang_digunakan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoPerkembangan',
        ),
    ]
